title: 1X Discover
description: Get help with 1X Studios Services and learn open source documentation
theme: just-the-docs

url: https://help.1xstudios.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template